server:
  port: 8761
eureka:
  instance:
    hostname: 211.159.165.227
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/